### PR TITLE
fix race condition when setting hash

### LINKED ISSUE #9: make new() thread safe
https://github.com/axiomhq/hyperloglog/blob/master/hyperloglog.go#L50 is not threadsafe (compile with -race and run in a multi-threaded program to detect it). this can be worked around by adding a package init function. 

    func init() {
        hash = hashFunc
    }

the new() function is not threadsafe because it is modifying a module level variable without locks

### PR DESCRIPTION
**Pull request by seiflotfy**
Fixes #9

### CODE REVIEW

**Comment by seiflotfy** [comment]
@RaduBerinde @okayzed WDYT?

**Comment by okayzed** [comment]
you managed to turn 3 lines and a blankline into 25+ lines of code, i think it can be more elegant

**Comment by seiflotfy** [comment]
elegance is over-rated

**Comment by RaduBerinde** [comment]
LGTM, thanks!

**Pull request merged**
